/* Generated By:JavaCC: Do not edit this line. MdlParser.java */

import java.util.*;
import java.io.*;

import parser.*;
import parseTables.*;

public class mdl 
{
  public static void main(String args[]) throws ParseException 
    {
	ArrayList a;	
	SymTab s;
	MdlParser parser;
	String file;

	if ( args.length == 1 )
	    file = args[0];
	else
	    file = "test.mdl";
	try {
	    parser = new MdlParser(new FileReader( file ));
	}
	catch ( IOException e ) {
	    parser = new MdlParser(System.in);
	}
	
	parser.start();
	a = parser.getOps();
	s = parser.getSymTab();

	MDLReader mr = new MDLReader( a, s);
	mr.process();
	

	/* Test MDLParser
	System.out.println("Opcodes:");
	Iterator i = a.iterator();
	while (i.hasNext())
	    {
		System.out.println(i.next());
	    }
	System.out.println("\n\n");
	SymTab s = parser.getSymTab();
	Set kset = s.keySet();
	i=kset.iterator();
	System.out.println("Symbol Table:");
	while (i.hasNext())
	    {
		String key = (String)i.next();
		Object value=s.get(key);
		System.out.println(""+key+"="+value);
	    }
	*/
    }
}
